version: "3"
services:
  plak-zookeeper-i:
    image: confluentinc/cp-zookeeper:latest
    container_name: plak-zookeeper-i
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  plak-zookeeper-ii:
    image: confluentinc/cp-zookeeper:latest
    container_name: plak-zookeeper-ii
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "32181:2181"

  plak-broker-i:
    image: confluentinc/cp-kafka:latest
    container_name: plak-broker-i
    ports:
      - "19092:9092"
    depends_on:
      - plak-zookeeper-i
      - plak-zookeeper-ii
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: "plak-zookeeper-i:2181,plak-zookeeper-ii:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://plak-broker-i:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  plak-broker-ii:
    image: confluentinc/cp-kafka:latest
    container_name: plak-broker-ii
    ports:
      - "19093:9092"
    depends_on:
      - plak-zookeeper-i
      - plak-zookeeper-ii
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: "plak-zookeeper-i:2181,plak-zookeeper-ii:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://plak-broker-ii:9093,PLAINTEXT_HOST://localhost:19093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  plak-broker-iii:
    image: confluentinc/cp-kafka:latest
    container_name: plak-broker-iii
    ports:
      - "19094:9092"
    depends_on:
      - plak-zookeeper-i
      - plak-zookeeper-ii
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: "zplak-zookeeper-i:2181,plak-zookeeper-ii:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://plak-broker-iii:9094,PLAINTEXT_HOST://localhost:19094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
